// <auto-generated />
using System;
using API.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SmartCV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524181438_AddOffreHashToGapSession")]
    partial class AddOffreHashToGapSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("API.models.AnalyseOffre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("APostule")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("CompetencesManquantes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("CompetencesMatch")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("CompetencesRequises")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateAnalyse")
                        .HasColumnType("timestamp without time zone");

                    b.PrimitiveCollection<string>("MotsClesExtraits")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OffreId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfilId")
                        .HasColumnType("integer");

                    b.Property<string>("Recommandations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ScoreCompatibilite")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OffreId");

                    b.HasIndex("ProfilId");

                    b.ToTable("AnalysesOffre");
                });

            modelBuilder.Entity("API.models.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CVId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("OffreId")
                        .HasColumnType("integer");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("enregistree");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.HasIndex("OffreId");

                    b.HasIndex("UserId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("API.models.Certificat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateObtention")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstValide")
                        .HasColumnType("boolean");

                    b.Property<string>("Identifiant")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LienVerification")
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Organisme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfilId");

                    b.HasIndex("UserId");

                    b.ToTable("Certificats");
                });

            modelBuilder.Entity("API.models.Competence", b =>
                {
                    b.Property<int>("IdComp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComp"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer");

                    b.HasKey("IdComp");

                    b.HasIndex("ProfilId", "Nom")
                        .IsUnique();

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("API.models.Cv", b =>
                {
                    b.Property<int>("IdCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCv"));

                    b.Property<int>("AnalyseOffreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAnalyse")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Exigences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OffreId")
                        .HasColumnType("integer");

                    b.Property<float>("ScoreCompatibilite")
                        .HasColumnType("real");

                    b.Property<string>("SkillsDetectes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("BROUILLON");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IdCv");

                    b.HasIndex("AnalyseOffreId");

                    b.HasIndex("OffreId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Cvs");
                });

            modelBuilder.Entity("API.models.CvPdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CvId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("CvPdf");
                });

            modelBuilder.Entity("API.models.CvPersonnalise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenuJson")
                        .HasColumnType("text");

                    b.Property<string>("CouleurPrimaire")
                        .HasColumnType("text");

                    b.Property<string>("CouleurSecondaire")
                        .HasColumnType("text");

                    b.Property<string>("CouleurTexte")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Police")
                        .HasColumnType("text");

                    b.Property<string>("TaillePolice")
                        .HasColumnType("text");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("CvsPersonnalises");
                });

            modelBuilder.Entity("API.models.Experience", b =>
                {
                    b.Property<int>("IdExp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExp"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer");

                    b.HasKey("IdExp");

                    b.HasIndex("ProfilId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("API.models.Formation", b =>
                {
                    b.Property<int>("IdFrmt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFrmt"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<string>("Diplome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etablissement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mention")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer");

                    b.HasKey("IdFrmt");

                    b.HasIndex("ProfilId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("API.models.GapSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Entreprise")
                        .HasColumnType("text");

                    b.Property<string>("OffreHash")
                        .HasColumnType("text");

                    b.Property<int>("ScoreCompatibilite")
                        .HasColumnType("integer");

                    b.Property<string>("TexteOffre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitreOffre")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GapSessions");
                });

            modelBuilder.Entity("API.models.GapSessionSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GapSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("NomCompetence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoadmapId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GapSessionId");

                    b.HasIndex("RoadmapId");

                    b.ToTable("GapSessionSkills");
                });

            modelBuilder.Entity("API.models.LettreMotivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int?>("CvId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int>("OffreId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("OffreId");

                    b.HasIndex("UserId");

                    b.ToTable("LettresMotivation");
                });

            modelBuilder.Entity("API.models.LigneDynamique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("LignesDynamiques");
                });

            modelBuilder.Entity("API.models.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exigences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlOffre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Offres");
                });

            modelBuilder.Entity("API.models.Profil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profils");
                });

            modelBuilder.Entity("API.models.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completee")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EtapesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NiveauDepart")
                        .HasColumnType("integer");

                    b.Property<string>("NomCompetence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RoadmapSuivie")
                        .HasColumnType("boolean");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("API.models.SectionDynamique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfilId");

                    b.ToTable("SectionsDynamiques");
                });

            modelBuilder.Entity("API.models.TemplateCv", b =>
                {
                    b.Property<int>("IdTemp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTemp"));

                    b.Property<string>("ApercuUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lignes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StructureJson")
                        .HasColumnType("text");

                    b.HasKey("IdTemp");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("API.models.TestCompetence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NiveauDetecte")
                        .HasColumnType("integer");

                    b.Property<string>("NomCompetence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReponsesJson")
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TestsCompetences");
                });

            modelBuilder.Entity("API.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Candidat");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.models.Admin", b =>
                {
                    b.HasOne("API.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.AnalyseOffre", b =>
                {
                    b.HasOne("API.models.Offre", "Offre")
                        .WithMany("Analyses")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.models.Profil", "Profil")
                        .WithMany()
                        .HasForeignKey("ProfilId");

                    b.Navigation("Offre");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("API.models.Candidature", b =>
                {
                    b.HasOne("API.models.Cv", "Cv")
                        .WithMany("Candidatures")
                        .HasForeignKey("CVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.models.Offre", null)
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreId");

                    b.HasOne("API.models.User", "User")
                        .WithMany("Candidatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.Certificat", b =>
                {
                    b.HasOne("API.models.Profil", "Profil")
                        .WithMany("Certificats")
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.models.User", null)
                        .WithMany("Certificats")
                        .HasForeignKey("UserId");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("API.models.Competence", b =>
                {
                    b.HasOne("API.models.Profil", "Profil")
                        .WithMany("Competences")
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("API.models.Cv", b =>
                {
                    b.HasOne("API.models.AnalyseOffre", "AnalyseOffre")
                        .WithMany()
                        .HasForeignKey("AnalyseOffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.models.Offre", "Offre")
                        .WithMany()
                        .HasForeignKey("OffreId");

                    b.HasOne("API.models.TemplateCv", "Template")
                        .WithMany("Cvs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.models.User", "User")
                        .WithMany("Cvs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalyseOffre");

                    b.Navigation("Offre");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.CvPdf", b =>
                {
                    b.HasOne("API.models.CvPersonnalise", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("API.models.CvPersonnalise", b =>
                {
                    b.HasOne("API.models.TemplateCv", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.Experience", b =>
                {
                    b.HasOne("API.models.Profil", "Profil")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("API.models.Formation", b =>
                {
                    b.HasOne("API.models.Profil", "Profil")
                        .WithMany("Formations")
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("API.models.GapSession", b =>
                {
                    b.HasOne("API.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.GapSessionSkill", b =>
                {
                    b.HasOne("API.models.GapSession", "GapSession")
                        .WithMany("Skills")
                        .HasForeignKey("GapSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.models.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GapSession");

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("API.models.LettreMotivation", b =>
                {
                    b.HasOne("API.models.Cv", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.models.Offre", "Offre")
                        .WithMany("LettresMotivation")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.models.User", "User")
                        .WithMany("LettresMotivation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("Offre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.LigneDynamique", b =>
                {
                    b.HasOne("API.models.SectionDynamique", "Section")
                        .WithMany("Lignes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("API.models.Profil", b =>
                {
                    b.HasOne("API.models.User", "User")
                        .WithOne("Profil")
                        .HasForeignKey("API.models.Profil", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.Roadmap", b =>
                {
                    b.HasOne("API.models.TestCompetence", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.SectionDynamique", b =>
                {
                    b.HasOne("API.models.Profil", "Profil")
                        .WithMany("Sections")
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("API.models.TestCompetence", b =>
                {
                    b.HasOne("API.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.models.Cv", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("API.models.GapSession", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("API.models.Offre", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Candidatures");

                    b.Navigation("LettresMotivation");
                });

            modelBuilder.Entity("API.models.Profil", b =>
                {
                    b.Navigation("Certificats");

                    b.Navigation("Competences");

                    b.Navigation("Experiences");

                    b.Navigation("Formations");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("API.models.SectionDynamique", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("API.models.TemplateCv", b =>
                {
                    b.Navigation("Cvs");
                });

            modelBuilder.Entity("API.models.User", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Certificats");

                    b.Navigation("Cvs");

                    b.Navigation("LettresMotivation");

                    b.Navigation("Profil")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
